### ISSUE TITLE
n-dimensional groupby

### ISSUE THREAD

**Issue by max-sixty** [shoyer/numbagg#12]
Currently I think `group_nanmean` expects labels in the same dimension as values

Is that right? What would it take to change this to instead broadcast labels from a number of one-dimensional arrays?

Could we have a separate `sparse_to_dense` function to transform a list of arrays (i.e. `[n,m]`) to a single array (i.e. `n x m`)? We could factorize at the same time. But not sure whether such a function would have a reasonable signature? And this could require a significant memory overhead vs the groupby function operating on a dense array

**Comment by max-sixty** [comment]
Similar to https://github.com/shoyer/numbagg/issues/8

**Comment by shoyer** [comment]
> Could we have a separate `sparse_to_dense` function to transform a list of arrays (i.e. `[n,m]`) to a single array (i.e. `n x m`)? We could factorize at the same time. But not sure whether such a function would have a reasonable signature? And this could require a significant memory overhead vs the groupby function operating on a dense array

I think this is probably the right approach. A good starting point would be to start with xarray's `.stack()` method.

The trouble with broadcasting labels from a number of one-dimensional arrays is that then we need to compile functions with a variadic number of argument. I'm pretty sure that isn't possible in Numba.

But if need be, we could hard-code functions that handle fixed numbers of arrays. That could speed up the most common operations (which only group over a few arguments).

**Comment by max-sixty** [comment]
>The trouble with broadcasting labels from a number of one-dimensional arrays is that then we need to compile functions with a variadic number of argument. I'm pretty sure that isn't possible in Numba.

Numba does accept lists as arguments (I think) so we could pass a list of 1D arrays?

**Comment by max-sixty** [comment]
> A good starting point would be to start with xarray's `.stack()` method.

I agree. I'm struggling a bit to build the algo atm...

**Comment by max-sixty** [comment]
Closing given the progress from numpy groupies https://github.com/ml31415/numpy-groupies, and our plans to explore using that in xarray
