### ISSUE TITLE
try other JITs

### ISSUE THREAD

**Issue by jennolsen84** [shoyer/numbagg#2]
It will be interesting to bench jitpy vs numba:

http://jitpy.readthedocs.org/en/latest/

If the pypy people can generate better code, it might be worthwhile to use their implementations too.

Though, I think you might be able to compose numba jitted functions together very nicely without coming back into python space.  I am not sure if this will be the case if some of the functions are numba, and others are jitpy

**Comment by shoyer** [comment]
It would indeed be interesting to see how these benchmarks compare, e.g., for 1d input.

For my goals with this project (for which I do eventually intend to make a release), numba's support for handling n-dimensional input (e.g., with `ndarray.flat`, `vectorize` and generalized ufuncs) is very convenient, and unfortunately, I don't think those are planned features for jitpy. Also, based on the jitpy benchmarks, it looks like numba is usually a bit faster for cases that it can accelerate (which include all those I currently have).

**Comment by jennolsen84** [comment]
OK, I just wanted to bring it to your attention, feel free to close the issue if you'd like
