### ISSUE TITLE
Best way to add move_exp_nansum

### ISSUE THREAD

**Issue by max-sixty** [shoyer/numbagg#26]
I'd like to implement a exp-rolling sum, similar to https://github.com/shoyer/numbagg/blob/master/numbagg/moving.py#L8, but without the denominator. A couple of options for how to approach:

- Copy and paste the 35 lines and remove the denominator
- Add an argument to the `move_exp_nanmean` function
- (I had thought "multiply by the denominator" would work, but now I don't think that's possible for the beginning of the result, before the denominator has reached steady-state)

**Comment by shoyer** [comment]
In theory a good JIT would just compile two different versions of the code for a boolean argument. I don't know if Numba does that, though.

So I would lean towards testing that, and if it fails, falling back to copy & paste (with a comment noting the differences).
